-- MySQL Script generated by MySQL Workbench
-- 02/25/17 07:40:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rrhh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rrhh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rrhh` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `rrhh` ;

-- -----------------------------------------------------
-- Table `rrhh`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rrhh`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(64) NOT NULL,
  `apellido` VARCHAR(64) NOT NULL,
  `cedula` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `rol` ENUM('rrhh', 'aspirante') NOT NULL,
  `correo` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rrhh`.`archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rrhh`.`archivo` (
  `id_archivo` INT NOT NULL,
  `url` VARCHAR(128) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_archivo`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  INDEX `fk_archivo_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_archivo_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `rrhh`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
